import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins, Inter } from 'next/font/google';
import Navbar from "./component/navbar";
import contenido from "../../public/contenido.json";

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600', '700'], variable: '--font-poppins' });
const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const titulo = contenido?.empresa?.nombre ?? "Nova Web Studio";
export const metadata: Metadata = {
  title: titulo,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const empresa = contenido?.empresa?.nombre ?? "Nova Web Studio";
  return (
        <html lang="es" className={`${poppins.variable} ${inter.variable}`}>
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased font-sans` }
      ><Navbar name={empresa} links={contenido.navbar.links} />
        {children}
      </body>
    </html>
  );
}
